theme = "gruvbox_custom"

[editor]
true-color = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal.space]
l = ":toggle-option whitespace.render all none"
m = ":toggle-option mouse"
x = ":toggle-option cursorline"
z = ":toggle-option line-number relative absolute"
