#!/usr/bin/env python
from subprocess import call

color_fg_normal = '#f9f9f9'
color_fg_focused = color_fg_normal
color_bg_normal = '#2d2d2d'
color_bg_focused = '#00612b'
color_urgent = '#610000'
color_sticky_focused = '#030061'

config = {
    'focused_border_color': color_bg_focused,
    'normal_border_color': color_bg_normal,
    'urgent_border_color': color_urgent,
    'focused_sticky_border_color': color_sticky_focused,

    'top_padding': '18',
    'border_width': '2',
    'window_gap': '19',

    'focus_follows_pointer': 'true',
    'pointer_follows_monitor': 'true',
    'split_ratio': '0.50',
    'borderless_monocle': 'true',
    'gapless_monocle': 'true',
    'focus_by_distance': 'true',
    'ignore_ewmh_focus': 'true'
}

rules = {
    'URxvt': 'desktop=^2 follow=on floating=on'
}
bspc_cmd = '/usr/bin/bspc'

call([bspc_cmd, 'monitor', '-d', '1', '2', '3', '4', '5'])

for key, value in config.items():
    call([bspc_cmd, 'config', key, value])

for key, value in rules.items():
    call([bspc_cmd, 'rule', '-a', key, value])
