#!/usr/bin/env bash
xkbcomp $DISPLAY - | egrep -v "group . = AltGr;" | xkbcomp - $DISPLAY
if [[ -z $(pgrep nm-applet) ]]; then
	nm-applet 2>&1 >/dev/null  &
fi
if [[ -z $(pgrep roccateventhandler) ]]; then
	roccateventhandler 2>&1 >/dev/null &
fi
#if [[ -z $(pgrep jackd) ]]; then
#    /usr/bin/jackd -R -dalsa -dhw:CODEC -r44100 -p256 -n3 &
#fi
