#! /bin/sh
export _JAVA_AWT_WM_NONREPARENTING=1

bspc config border_width            2
bspc config window_gap              2

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true
bspc config top_padding             16

screens=$(xrandr|grep ' connected')
primary=$(awk '{if ($3 == "primary") print $1}' <<< $screens)
secondary=$(awk '{if ($3 != "primary") print $1}' <<< $screens)
bspc monitor    $primary -d         1 2 3
bspc monitor    $secondary -d       q w e

wmname "LG3D"

#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
