[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = '|'
idle_bg = "#2c2c2c"
idle_fg = "#ebdbb2"
info_bg = "#2c2c2c"
info_fg = "#458588"
good_bg = "#2c2c2c"
good_fg = "#98971a"
warning_bg = "#2c2c2c"
warning_fg = "#d79921"
critical_bg = "#2c2c2c"
critical_fg = "#cc241d"
separator_bg = "#2c2c2c"
separator_fg = "#3c3836"

[icons]
icons = "awesome4"

[[block]]
block = "disk_space"
path = "/"
warning = 10.0
alert = 5.0

[[block]]
block = "cpu"
interval = 1

#[[block]]
#block = "sound"
#on_click = "pavucontrol"
#step_width = 2

[[block]]
block = "keyboard_layout"
driver = "sway"

#[[block]]
#block = "custom"
#command = "printf \uf019"
#on_click = "screenshot-tool file"
#interval = 60

#[[block]]
#block = "custom"
#command = "printf \uf0ea"
#on_click = "screenshot-tool"
#interval = 60

[[block]]
block = "time"
interval = 5
