#!/usr/bin/env bash

source "$HOME/.config/bspwm/common"

#xsetroot -cursor_name left_ptr

bspc config focused_border_color            "#$colour_bg_focused"
bspc config normal_border_color             "#$colour_bg_normal"
bspc config urgent_border_color             "#$colour_urgent"
bspc config focused_sticky_border_color     "#$colour_sticky_focused"
bspc config top_padding                     "$panel_h"
bspc config border_width                    "$bspwm_border_width"
bspc config window_gap                      "$bspwm_window_gap"

bspc config focus_follows_pointer           'true'
bspc config pointer_follows_monitor         'true'
bspc config split_ratio                     '0.50'
bspc config borderless_monocle              'true'
bspc config gapless_monocle                 'true'
bspc config focus_by_distance               'true'
bspc config ignore_ewmh_focus               'true'
#bspc config initial_polarity                'second_child'

bspc monitor -d                             1 2 3 4 5

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a mpv floating=on
