# -*- conf -*-

font=Maple Mono NL NF:size=12
box-drawings-uses-font-glyphs=no
# dpi-aware=yes

bold-text-in-bright=no
word-delimiters=,│`|:"'()[]{}<>

[bell]
urgent=no
notify=no

[scrollback]
lines=15000

[mouse]
hide-when-typing=no

[key-bindings]
clipboard-copy=Mod1+c XF86Copy
clipboard-paste=Mod1+v XF86Paste

[mouse-bindings]
select-begin-block=Mod1+BTN_LEFT

# vim: ft=conf
