[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = '|'
idle_bg = "#2c2c2c"
idle_fg = "#ebdbb2"
info_bg = "#2c2c2c"
info_fg = "#458588"
good_bg = "#2c2c2c"
good_fg = "#98971a"
warning_bg = "#2c2c2c"
warning_fg = "#d79921"
critical_bg = "#2c2c2c"
critical_fg = "#cc241d"
separator_bg = "#2c2c2c"
separator_fg = "#3c3836"

[icons]
icons = "awesome4"

[[block]]
block = "net"
format = " $icon "

[[block]]
block = "cpu"
format = " $icon "

[[block]]
block = "memory"
format = " $icon "

[[block]]
block = "keyboard_layout"
driver = "sway"
[block.mappings]
"English (US)" = "EN"
"Russian (typewriter)" = "RU"

[[block]]
block = "time"
interval = 1
timezone = "Europe/Moscow"
[block.format]
full = " $timestamp.datetime(f:'%R') "
